#recording
board 5 2 false
board 4 3 false
board 4 3 false
board 4 3 false
token 28
board 6 4 false
board 6 4 false
board 4 3 false
token 27
board 5 3 false
board 5 3 false
board 4 3 false
token 26
board 5 3 false
board 5 3 false
board 4 3 false
token 14
board 5 3 false
board 5 3 false
board 4 3 false
token 25
board 5 3 false
board 5 3 false
board 6 4 false
board 10 4 true
board 10 5 false
board 10 6 false
board 10 6 false
board 10 6 false
token 14
board 11 5 false
board 11 5 false
board 10 6 false
token 25
board 9 6 false
board 9 6 false
board 9 6 false
board 11 7 true
board 11 5 false
board 11 5 false
board 11 5 false
board 10 6 false
board 10 6 false
board 10 6 false
board 11 6 false
board 12 6 false
board 13 6 false
board 13 6 false
board 12 6 false
token 26
board 11 6 false
board 11 6 false
board 12 6 false
token 27
board 11 6 false
board 11 6 false
board 11 6 false
action EvtFire
board 9 6 false
board 10 9 false
board 10 9 false
board 13 6 false
board 14 7 false
board 14 7 false
board 14 7 false
token 14
board 15 7 false
board 15 7 false
board 15 7 false
board 12 9 true
board 11 6 false
board 11 6 false
board 11 6 false
board 11 7 false
board 11 7 false
board 11 7 false
action EvtRepair
