/**
 * 
 */
package com.fullmetalgalaxy.model.persist.triggers.actions;

import java.util.ArrayList;
import java.util.List;

import com.fullmetalgalaxy.model.persist.EbBase;
import com.fullmetalgalaxy.model.persist.EbGame;
import com.fullmetalgalaxy.model.persist.gamelog.AnEvent;


/**
 * @author Vincent Legendre
 *
 */
public class AnAction extends EbBase
{
  static final long serialVersionUID = 122;

  /**
   * 
   */
  public AnAction()
  {
    init();
  }

  /**
   * @param p_base
   */
  public AnAction(EbBase p_base)
  {
    super( p_base );
    init();
  }


  private void init()
  {
  }

  @Override
  public void reinit()
  {
    super.reinit();
    this.init();
  }

  // main trigger action interface
  // --------------------------------
  /**
   * to be overloaded
   * @param p_game is the game where to build events
   * @param p_params a list of parameters which are generated by conditions.
   * @return a list of all events this action do. note that these events have been executed.
   */
  public List<AnEvent> createEvents(EbGame p_game, List<Object> p_params)
  {
    List<AnEvent> events = new ArrayList<AnEvent>();
    return events;
  }

}
