/* *********************************************************************
 *
 *  This file is part of Full Metal Galaxy.
 *  http://www.fullmetalgalaxy.com
 *
 *  Full Metal Galaxy is free software: you can redistribute it and/or 
 *  modify it under the terms of the GNU Affero General Public License
 *  as published by the Free Software Foundation, either version 3 of 
 *  the License, or (at your option) any later version.
 *
 *  Full Metal Galaxy is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public 
 *  License along with Full Metal Galaxy.  
 *  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Copyright 2010, 2011, 2012, 2013 Vincent Legendre
 *
 * *********************************************************************/
package com.fullmetalgalaxy.model.persist.triggers.actions;

import java.util.ArrayList;
import java.util.List;

import com.fullmetalgalaxy.model.persist.EbBase;
import com.fullmetalgalaxy.model.persist.Game;
import com.fullmetalgalaxy.model.persist.gamelog.AnEvent;


/**
 * @author Vincent Legendre
 *
 */
public class AnAction extends EbBase
{
  static final long serialVersionUID = 122;

  /**
   * 
   */
  public AnAction()
  {
    init();
  }

  /**
   * @param p_base
   */
  public AnAction(EbBase p_base)
  {
    super( p_base );
    init();
  }


  private void init()
  {
  }

  @Override
  public void reinit()
  {
    super.reinit();
    this.init();
  }

  // main trigger action interface
  // --------------------------------
  /**
   * to be overloaded
   * @param p_game is the game where to build events
   * @param p_params a list of parameters which are generated by conditions.
   * @return a list of all events this action do. note that these events have been executed.
   */
  public List<AnEvent> createEvents(Game p_game, List<Object> p_params)
  {
    List<AnEvent> events = new ArrayList<AnEvent>();
    return events;
  }

}
